/* =============================================================================
   i18n engine + translations for RecoverySync web pages
   To add a new language: add a new top-level key to TRANSLATIONS,
   then add a <button class="lang-btn" data-lang="XX"> in each HTML file.
   ============================================================================= */

const TRANSLATIONS = {

  /* ── English ─────────────────────────────────────────────────────────────── */
  en: {
    /* Nav */
    "nav.product":  "RecoverySync",
    "nav.privacy":  "Privacy",
    "nav.support":  "Support",
    "nav.terms":    "Terms",
    "lang.en":      "EN",
    "lang.ja":      "JA",

    /* Footer */
    "footer.copyright": "© 2026 RecoverySync",
    "footer.rights":    "All rights reserved.",

    /* ── Privacy page ─────────────────────────────────────────────────────── */
    "privacy.page-title":    "Privacy Policy — RecoverySync",
    "privacy.title":         "Privacy Policy",
    "privacy.updated":       "Last updated: May 2026",
    "privacy.badge":         "Data Not Collected",
    "privacy.intro":         "RecoverySync is built on a simple principle: your health data belongs to you. We do not collect, transmit, or share any personal or health data with anyone — not with us, not with third parties, not with advertisers.",

    "privacy.s1.title":      "What data we access",
    "privacy.s1.body":       "With your permission, RecoverySync reads the following data from Apple HealthKit on your device:",
    "privacy.s1.item1":      "Heart Rate Variability (RMSSD) — to calculate your recovery score",
    "privacy.s1.item2":      "Resting Heart Rate — to calculate your recovery score",
    "privacy.s1.item3":      "Sleep data — to calculate your recovery score",
    "privacy.s1.readonly":   "All access is read-only. RecoverySync never writes data back to HealthKit.",

    "privacy.s2.title":      "What we do NOT collect",
    "privacy.s2.body":       "RecoverySync does not collect any of the following:",
    "privacy.s2.item1":      "Names, email addresses, or account information",
    "privacy.s2.item2":      "Location data",
    "privacy.s2.item3":      "IP addresses or device identifiers",
    "privacy.s2.item4":      "Analytics or usage data",
    "privacy.s2.item5":      "Crash reports sent to third-party services",
    "privacy.s2.item6":      "Advertising identifiers",

    "privacy.s3.title":      "Where your data is stored",
    "privacy.s3.body":       "All data generated by RecoverySync — including your recovery scores and preferences — is stored exclusively on your device using Apple's SwiftData framework. No data is ever transmitted to external servers. iCloud Backup of your device may include this data at your discretion under your own Apple ID and Apple's privacy terms.",

    "privacy.s4.title":      "Third-party SDKs and services",
    "privacy.s4.body":       "RecoverySync contains no third-party analytics SDKs, advertising SDKs, or tracking libraries. The only external framework used is Apple's HealthKit, which is governed by Apple's own privacy policies.",

    "privacy.s5.title":      "Apple HealthKit",
    "privacy.s5.body":       "Health data obtained through HealthKit is used solely for the purpose of calculating and displaying your recovery score within the app. This data is never used for advertising, shared with data brokers, or disclosed to third parties.",

    "privacy.s6.title":      "Children",
    "privacy.s6.body":       "RecoverySync is not directed at children under the age of 13 and does not knowingly collect information from children.",

    "privacy.s7.title":      "Changes to this policy",
    "privacy.s7.body":       "If we make material changes to this privacy policy, we will update the \"Last updated\" date above. Continued use of the app after such changes constitutes your acceptance of the updated policy.",

    "privacy.s8.title":      "Contact",
    "privacy.s8.body":       "If you have questions about this privacy policy, please contact us:",
    "privacy.s8.email":      "support@recoverysync.app",

    /* ── Terms page ───────────────────────────────────────────────────────── */
    "terms.page-title":      "Terms of Use — RecoverySync",
    "terms.title":           "Terms of Use",
    "terms.updated":         "Last updated: May 2026",
    "terms.intro":           "These Terms of Use govern your use of RecoverySync (the \"App\"). By downloading or using the App, you agree to these terms.",

    "terms.s1.title":        "1. License",
    "terms.s1.body":         "Subject to these terms, we grant you a personal, non-exclusive, non-transferable, revocable license to use the App on Apple devices that you own or control, for personal, non-commercial purposes.",

    "terms.s2.title":        "2. Purchase and Payment",
    "terms.s2.item1":        "RecoverySync is available as a one-time purchase ($4.99 / ¥780) through Apple's App Store.",
    "terms.s2.item2":        "All purchases are processed by Apple. Refunds are subject to Apple's standard refund policy.",
    "terms.s2.item3":        "Prices may vary by region and are subject to change.",

    "terms.s3.title":        "3. Health Disclaimer",
    "terms.s3.body":         "RecoverySync is designed to provide general wellness information based on data from Apple Watch. It is NOT a medical device and does NOT provide medical advice, diagnosis, or treatment. Recovery scores are informational estimates only. Always consult a qualified healthcare professional before making decisions about your health, training, or exercise program.",

    "terms.s4.title":        "4. HealthKit Data",
    "terms.s4.body":         "The App reads health data from Apple HealthKit solely to calculate your recovery score. You can revoke Health access at any time in iOS Settings > Privacy & Security > Health.",

    "terms.s5.title":        "5. Restrictions",
    "terms.s5.body":         "You may not:",
    "terms.s5.item1":        "Reverse engineer, decompile, or disassemble the App",
    "terms.s5.item2":        "Use the App for commercial purposes without written permission",
    "terms.s5.item3":        "Attempt to circumvent any security or access controls",

    "terms.s6.title":        "6. No Warranty",
    "terms.s6.body":         "The App is provided \"as is\" without warranty of any kind. The accuracy of recovery scores depends on the quality of data provided by your Apple Watch hardware and HealthKit. We make no guarantee that scores accurately reflect your physiological state.",

    "terms.s7.title":        "7. Limitation of Liability",
    "terms.s7.body":         "To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the App.",

    "terms.s8.title":        "8. Governing Law",
    "terms.s8.body":         "These terms are governed by the laws of the State of California, USA, without regard to conflict of law principles. For users in Japan, applicable Japanese consumer protection laws apply in addition to these terms.",

    "terms.s9.title":        "9. Changes to Terms",
    "terms.s9.body":         "We may update these terms from time to time. We will update the \"Last updated\" date above. Continued use of the App after changes constitutes acceptance of the updated terms.",

    "terms.s10.title":       "10. Contact",
    "terms.s10.body":        "Questions about these terms:",
    "terms.s10.email":       "support@recoverysync.app",

    /* ── Support page ─────────────────────────────────────────────────────── */
    "support.page-title":    "Support — RecoverySync",
    "support.title":         "Support",
    "support.subtitle":      "We're here to help. Most questions are answered in the FAQ below.",
    "support.contact.title": "Contact Support",
    "support.contact.desc":  "Typically responds within 1–2 business days.",
    "support.contact.btn":   "Send Email",
    "support.faq.title":     "Frequently Asked Questions",

    "support.faq.q1":  "How does the recovery score work?",
    "support.faq.a1":  "Your recovery score is calculated from three metrics read from Apple Watch: Heart Rate Variability (HRV, RMSSD) accounts for 50%, Resting Heart Rate accounts for 30%, and Sleep Duration accounts for 20%. Each metric is compared to your personal 28-day baseline (established after a 14-day calibration period) to produce a score from 0–100. HIGH is 76–100, MODERATE is 51–75, and LOW is 0–50.",

    "support.faq.q2":  "Why is my score showing \"—\" (dash)?",
    "support.faq.a2":  "The app needs at least 7 nights of Apple Watch sleep data to begin calibration. During the initial calibration period (up to 14 days), the score will display \"—\". Make sure to wear your Apple Watch while sleeping every night to speed up calibration.",

    "support.faq.q3":  "Does RecoverySync work without an Apple Watch?",
    "support.faq.a3":  "No. RecoverySync requires Apple Watch (Series 4 or later) to record the HRV, resting heart rate, and sleep data used for score calculation. The iPhone app displays and analyzes the data, but the Apple Watch is the required data source.",

    "support.faq.q4":  "Why does the app need access to my Health data?",
    "support.faq.a4":  "RecoverySync reads HRV (RMSSD), resting heart rate, and sleep data from Apple HealthKit to calculate your recovery score. This is the only purpose for which health data is used. The data is processed entirely on-device and never leaves your iPhone.",

    "support.faq.q5":  "How do I restore my purchase?",
    "support.faq.a5":  "Open RecoverySync and go to Settings → Restore Purchase. Make sure you are signed in to the same Apple ID used for the original purchase. If the issue persists, contact Apple Support for purchase-related assistance.",

    "support.faq.q6":  "Does the app sync data to iCloud or any server?",
    "support.faq.a6":  "No. RecoverySync stores all data locally on your device only. There is no cloud sync, no account, and no server. Your data never leaves your device (unless included in your iCloud device backup, which is controlled by your iOS settings).",

    "support.faq.q7":  "My Apple Watch complication is not showing — how do I fix it?",
    "support.faq.a7":  "Open the Watch app on your iPhone → My Watch tab → scroll to RecoverySync → tap it → make sure the complication is added to your active watch face. You can also long-press your watch face → Edit → select a complication slot → choose RecoverySync.",

    "support.faq.q8":  "What Apple Watch models are supported?",
    "support.faq.a8":  "RecoverySync requires Apple Watch Series 4 or later running watchOS 10.0 or later, paired with an iPhone running iOS 17.0 or later.",

    "support.compat.title": "Compatibility",

    /* ── Product page ─────────────────────────────────────────────────────── */
    "product.page-title":   "RecoverySync — Sleep & HRV Recovery Tracker",
    "product.eyebrow":      "For Apple Watch",
    "product.title":        "Know your recovery.\nTrain smarter.",
    "product.tagline":      "RecoverySync analyzes your HRV, resting heart rate, and sleep to deliver a single daily recovery score — right on your wrist.",
    "product.cta.store":    "Download on the App Store",
    "product.cta.learn":    "Learn more",

    "product.score.title":    "One score. Three signals.",
    "product.score.subtitle": "Your recovery score is calculated from the health data your Apple Watch records while you sleep.",
    "product.level.high":     "HIGH",
    "product.level.mod":      "MODERATE",
    "product.level.low":      "LOW",
    "product.metric.hrv":     "Heart Rate Variability",
    "product.metric.rhr":     "Resting Heart Rate",
    "product.metric.sleep":   "Sleep Duration",

    "product.features.title":    "Built different.",
    "product.features.subtitle": "No subscriptions. No account. No data leaving your device.",
    "product.feat1.title":  "Privacy First",
    "product.feat1.desc":   "Zero data collection. Your health data stays on your device. No servers, no tracking, no ads.",
    "product.feat2.title":  "Apple Watch Native",
    "product.feat2.desc":   "Reads directly from HealthKit. Works with Apple Watch Series 4 and later, including complications and widgets.",
    "product.feat3.title":  "Morning Score",
    "product.feat3.desc":   "Get your personalized recovery score every morning. Optional notification delivers it before you start your day.",
    "product.feat4.title":  "Personal Baseline",
    "product.feat4.desc":   "After a short calibration period, scores are benchmarked against your own 28-day moving average — not population averages.",
    "product.feat5.title":  "One-Time Purchase",
    "product.feat5.desc":   "No subscription, no recurring charges. Pay once, use forever.",
    "product.feat6.title":  "Trend Analysis",
    "product.feat6.desc":   "Track your recovery trends over time with built-in charts. Export your data as CSV anytime.",

    "product.how.title":  "How it works",
    "product.step1.title": "Wear Apple Watch to sleep",
    "product.step1.desc":  "Sleep tracking and HRV recording happen automatically.",
    "product.step2.title": "Open the app in the morning",
    "product.step2.desc":  "Your recovery score is ready when you wake up.",
    "product.step3.title": "Read your score",
    "product.step3.desc":  "HIGH, MODERATE, or LOW — with a breakdown of each metric.",
    "product.step4.title": "Train accordingly",
    "product.step4.desc":  "Let your body guide your training intensity for the day.",

    "product.privacy.title": "Your data stays on your device.",
    "product.privacy.body":  "RecoverySync has a \"Data Not Collected\" privacy label on the App Store — the highest standard. No analytics, no crash tracking, no advertising. Your health data never leaves your iPhone.",
    "product.privacy.link":  "Read our Privacy Policy",

    "product.download.title":  "Start tracking your recovery",
    "product.download.body":   "Available on the App Store for iPhone and Apple Watch.",
    "product.download.price":  "$4.99 one-time · ¥780",
    "product.download.btn":    "Download on the App Store",
    "product.compat.title":    "Requires",
  },

  /* ── Japanese ─────────────────────────────────────────────────────────────── */
  ja: {
    /* Nav */
    "nav.product":  "RecoverySync",
    "nav.privacy":  "プライバシー",
    "nav.support":  "サポート",
    "nav.terms":    "利用規約",
    "lang.en":      "EN",
    "lang.ja":      "JA",

    /* Footer */
    "footer.copyright": "© 2026 RecoverySync",
    "footer.rights":    "All rights reserved.",

    /* ── プライバシーページ ──────────────────────────────────────────────── */
    "privacy.page-title":    "プライバシーポリシー — RecoverySync",
    "privacy.title":         "プライバシーポリシー",
    "privacy.updated":       "最終更新: 2026年5月",
    "privacy.badge":         "データ収集なし",
    "privacy.intro":         "RecoverySyncは「あなたの健康データはあなたのもの」という考えに基づいて設計されています。個人データおよび健康データを収集・送信・共有することは一切ありません。私たち自身も、第三者も、広告主も、いかなる相手にも提供しません。",

    "privacy.s1.title":      "アクセスするデータ",
    "privacy.s1.body":       "お客様の許可のもと、RecoverySyncはデバイス上のApple HealthKitから以下のデータを読み取ります:",
    "privacy.s1.item1":      "心拍変動（RMSSD）— リカバリースコアの算出のため",
    "privacy.s1.item2":      "安静時心拍数 — リカバリースコアの算出のため",
    "privacy.s1.item3":      "睡眠データ — リカバリースコアの算出のため",
    "privacy.s1.readonly":   "すべてのアクセスは読み取り専用です。RecoverySyncがHealthKitにデータを書き込むことはありません。",

    "privacy.s2.title":      "収集しないデータ",
    "privacy.s2.body":       "RecoverySyncは以下のデータを一切収集しません:",
    "privacy.s2.item1":      "氏名・メールアドレス・アカウント情報",
    "privacy.s2.item2":      "位置情報",
    "privacy.s2.item3":      "IPアドレスやデバイス識別子",
    "privacy.s2.item4":      "分析データや使用状況データ",
    "privacy.s2.item5":      "サードパーティサービスへのクラッシュレポート",
    "privacy.s2.item6":      "広告識別子",

    "privacy.s3.title":      "データの保存場所",
    "privacy.s3.body":       "リカバリースコアや設定を含む、RecoverySyncが生成するすべてのデータは、Appleのswiftdata形式でデバイス上のみに保存されます。外部サーバーへの送信は一切行いません。iCloudバックアップにこのデータが含まれるかどうかは、お客様ご自身のApple IDおよびAppleのプライバシー規約に従い、お客様がご自身で管理します。",

    "privacy.s4.title":      "サードパーティSDKおよびサービス",
    "privacy.s4.body":       "RecoverySyncにはサードパーティの分析SDK・広告SDK・トラッキングライブラリは含まれていません。使用している唯一の外部フレームワークはAppleのHealthKitであり、これはApple自身のプライバシーポリシーに準拠しています。",

    "privacy.s5.title":      "Apple HealthKitについて",
    "privacy.s5.body":       "HealthKitを通じて取得した健康データは、アプリ内でリカバリースコアを算出・表示する目的のみに使用します。広告目的での使用、データブローカーへの提供、第三者への開示は一切行いません。",

    "privacy.s6.title":      "お子様について",
    "privacy.s6.body":       "RecoverySyncは13歳未満のお子様を対象としておらず、お子様から意図的に情報を収集することはありません。",

    "privacy.s7.title":      "ポリシーの変更",
    "privacy.s7.body":       "プライバシーポリシーに重大な変更を加える場合、上記の「最終更新」日を更新します。変更後もアプリを継続して使用された場合、更新後のポリシーに同意したものとみなします。",

    "privacy.s8.title":      "お問い合わせ",
    "privacy.s8.body":       "プライバシーポリシーに関するご質問は、下記までご連絡ください:",
    "privacy.s8.email":      "support@recoverysync.app",

    /* ── 利用規約ページ ───────────────────────────────────────────────────── */
    "terms.page-title":      "利用規約 — RecoverySync",
    "terms.title":           "利用規約",
    "terms.updated":         "最終更新: 2026年5月",
    "terms.intro":           "本利用規約（以下「本規約」）は、RecoverySync（以下「本アプリ」）のご利用に適用されます。本アプリをダウンロードまたは使用することで、本規約に同意したものとみなします。",

    "terms.s1.title":        "1. 使用許諾",
    "terms.s1.body":         "本規約に従い、お客様が所有または管理するAppleデバイス上で、個人的・非商業的目的のために本アプリを使用する個人的・非独占的・譲渡不可・取消可能なライセンスを付与します。",

    "terms.s2.title":        "2. 購入および支払い",
    "terms.s2.item1":        "RecoverySyncはApple App Storeにて買い切り（$4.99 / ¥780）でご提供しています。",
    "terms.s2.item2":        "すべての購入処理はAppleが行います。払い戻しはAppleの標準的な返金ポリシーに従います。",
    "terms.s2.item3":        "価格は地域によって異なる場合があり、変更される可能性があります。",

    "terms.s3.title":        "3. 健康に関する免責事項",
    "terms.s3.body":         "RecoverySyncはApple Watchのデータに基づく一般的なウェルネス情報を提供することを目的としています。医療機器ではなく、医療上のアドバイス・診断・治療を提供するものではありません。リカバリースコアはあくまでも参考情報です。健康・トレーニング・運動プログラムに関する決定を行う前に、必ず資格を持つ医療専門家にご相談ください。",

    "terms.s4.title":        "4. HealthKitデータ",
    "terms.s4.body":         "本アプリはリカバリースコアの算出のみを目的として、Apple HealthKitから健康データを読み取ります。ヘルスアクセスはiOSの設定 → プライバシーとセキュリティ → ヘルスケアからいつでも取り消すことができます。",

    "terms.s5.title":        "5. 禁止事項",
    "terms.s5.body":         "以下の行為を禁止します:",
    "terms.s5.item1":        "本アプリのリバースエンジニアリング・逆コンパイル・逆アセンブル",
    "terms.s5.item2":        "書面による許可なく本アプリを商業目的で使用すること",
    "terms.s5.item3":        "セキュリティや アクセス制御を回避しようとする行為",

    "terms.s6.title":        "6. 無保証",
    "terms.s6.body":         "本アプリは「現状のまま」提供され、いかなる種類の保証も伴いません。リカバリースコアの精度はApple WatchハードウェアおよびHealthKitが提供するデータの品質に依存します。スコアがお客様の生理的状態を正確に反映することを保証するものではありません。",

    "terms.s7.title":        "7. 責任の制限",
    "terms.s7.body":         "法律で最大限許可される範囲において、本アプリの使用から生じる間接的・付随的・特別・派生的損害について、当社は一切の責任を負いません。",

    "terms.s8.title":        "8. 準拠法",
    "terms.s8.body":         "本規約は、抵触法の原則にかかわらず、米国カリフォルニア州の法律に準拠します。日本のユーザーの方には、本規約に加えて適用される日本の消費者保護法が適用されます。",

    "terms.s9.title":        "9. 規約の変更",
    "terms.s9.body":         "本規約は随時更新される場合があります。変更が生じた場合、上記の「最終更新」日を更新します。変更後もアプリを継続して使用された場合、更新後の規約に同意したものとみなします。",

    "terms.s10.title":       "10. お問い合わせ",
    "terms.s10.body":        "本規約に関するご質問:",
    "terms.s10.email":       "support@recoverysync.app",

    /* ── サポートページ ───────────────────────────────────────────────────── */
    "support.page-title":    "サポート — RecoverySync",
    "support.title":         "サポート",
    "support.subtitle":      "ご不明な点がございましたら、まず下記のよくある質問をご確認ください。",
    "support.contact.title": "サポートへのお問い合わせ",
    "support.contact.desc":  "通常、1〜2営業日以内にご回答いたします。",
    "support.contact.btn":   "メールを送る",
    "support.faq.title":     "よくある質問",

    "support.faq.q1":  "リカバリースコアはどのように計算されますか？",
    "support.faq.a1":  "リカバリースコアはApple Watchから取得した3つの指標をもとに算出されます。心拍変動（HRV、RMSSD）が50%、安静時心拍数が30%、睡眠時間が20%の割合で計算されます。各指標はお客様個人の28日間移動平均（14日間の較正期間後に確立）と比較され、0〜100のスコアが算出されます。76〜100がHIGH、51〜75がMODERATE、0〜50がLOWです。",

    "support.faq.q2":  "スコアが「—」（ダッシュ）と表示されるのはなぜですか？",
    "support.faq.a2":  "アプリの較正を開始するために、少なくとも7泊分のApple Watchによる睡眠データが必要です。初期較正期間（最大14日間）中は「—」と表示されます。較正を早めるために、毎晩Apple Watchを装着して就寝してください。",

    "support.faq.q3":  "Apple Watchなしで使用できますか？",
    "support.faq.a3":  "使用できません。RecoverySyncはスコア計算に使用するHRV・安静時心拍数・睡眠データを記録するためにApple Watch（Series 4以降）が必要です。iPhoneアプリはデータの表示と分析を行いますが、Apple Watchが必須のデータソースです。",

    "support.faq.q4":  "アプリにヘルスデータへのアクセスが必要なのはなぜですか？",
    "support.faq.a4":  "RecoverySyncはリカバリースコアを算出するために、Apple HealthKitからHRV（RMSSD）・安静時心拍数・睡眠データを読み取ります。これが健康データを使用する唯一の目的です。データはデバイス上で完全に処理され、iPhoneの外に出ることはありません。",

    "support.faq.q5":  "購入を復元するにはどうすればよいですか？",
    "support.faq.a5":  "RecoverySyncを開き、設定 → 購入を復元 の順にタップしてください。元の購入時に使用したApple IDでサインインしていることを確認してください。問題が解決しない場合は、購入に関するサポートについてAppleサポートにお問い合わせください。",

    "support.faq.q6":  "データはiCloudやサーバーに同期されますか？",
    "support.faq.a6":  "されません。RecoverySyncはすべてのデータをデバイス上のみに保存します。クラウド同期・アカウント・サーバーは一切ありません。お客様のデータはデバイスの外に出ることはありません（iOSの設定で有効にしているiCloudデバイスバックアップに含まれる場合を除きます）。",

    "support.faq.q7":  "Apple Watchのコンプリケーションが表示されません",
    "support.faq.a7":  "iPhoneのWatchアプリを開き、「マイウォッチ」タブ → RecoverySyncまでスクロール → タップして、コンプリケーションが現在のウォッチフェイスに追加されていることを確認してください。ウォッチフェイスを長押し → 編集 → コンプリケーションスロットを選択 → RecoverySyncを選択することもできます。",

    "support.faq.q8":  "対応しているApple Watchのモデルは？",
    "support.faq.a8":  "RecoverySyncはwatchOS 10.0以降を搭載したApple Watch Series 4以降が必要です。iOS 17.0以降を搭載したiPhoneとペアリングしてください。",

    "support.compat.title": "動作環境",

    /* ── 製品ページ ───────────────────────────────────────────────────────── */
    "product.page-title":   "RecoverySync — 睡眠・HRVリカバリートラッカー",
    "product.eyebrow":      "Apple Watch対応",
    "product.title":        "リカバリーを知り、\nスマートに鍛える。",
    "product.tagline":      "RecoverySyncはHRV・安静時心拍・睡眠を分析し、1日1回のリカバリースコアをあなたの手首に届けます。",
    "product.cta.store":    "App Storeでダウンロード",
    "product.cta.learn":    "詳しく見る",

    "product.score.title":    "1つのスコア、3つのシグナル。",
    "product.score.subtitle": "リカバリースコアは、就寝中にApple Watchが記録した健康データをもとに算出されます。",
    "product.level.high":     "HIGH",
    "product.level.mod":      "MODERATE",
    "product.level.low":      "LOW",
    "product.metric.hrv":     "心拍変動（HRV）",
    "product.metric.rhr":     "安静時心拍数",
    "product.metric.sleep":   "睡眠時間",

    "product.features.title":    "ここが違います。",
    "product.features.subtitle": "サブスクなし。アカウントなし。データはデバイスの外に出ません。",
    "product.feat1.title":  "プライバシー最優先",
    "product.feat1.desc":   "データ収集ゼロ。健康データはデバイス上に留まります。サーバーなし、トラッキングなし、広告なし。",
    "product.feat2.title":  "Apple Watchネイティブ",
    "product.feat2.desc":   "HealthKitから直接読み取り。Apple Watch Series 4以降、コンプリケーション、ウィジェットに対応。",
    "product.feat3.title":  "朝のスコア通知",
    "product.feat3.desc":   "毎朝、パーソナライズされたリカバリースコアを受け取れます。オプションの通知で1日が始まる前にお知らせします。",
    "product.feat4.title":  "個人ベースライン",
    "product.feat4.desc":   "短い較正期間の後、スコアは集団平均ではなくご自身の28日移動平均と比較されます。",
    "product.feat5.title":  "買い切り",
    "product.feat5.desc":   "サブスクなし、継続課金なし。一度購入すれば永続的に使用できます。",
    "product.feat6.title":  "トレンド分析",
    "product.feat6.desc":   "内蔵チャートでリカバリーの傾向を追跡できます。CSVとしていつでもエクスポート可能。",

    "product.how.title":   "使い方",
    "product.step1.title": "Apple Watchを装着して就寝",
    "product.step1.desc":  "睡眠トラッキングとHRVの記録は自動的に行われます。",
    "product.step2.title": "朝にアプリを開く",
    "product.step2.desc":  "起床時にリカバリースコアが準備できています。",
    "product.step3.title": "スコアを確認する",
    "product.step3.desc":  "HIGH・MODERATE・LOW、各指標の内訳とともに表示。",
    "product.step4.title": "スコアに合わせてトレーニング",
    "product.step4.desc":  "その日のトレーニング強度を体のシグナルに従って決めましょう。",

    "product.privacy.title": "データはデバイスの外に出ません。",
    "product.privacy.body":  "RecoverySyncはApp Storeで「データ収集なし」のプライバシーラベルを取得しています。分析なし、クラッシュ追跡なし、広告なし。健康データがiPhoneを離れることは一切ありません。",
    "product.privacy.link":  "プライバシーポリシーを読む",

    "product.download.title":  "リカバリーの追跡を始める",
    "product.download.body":   "iPhoneおよびApple Watch向けにApp Storeで配信中。",
    "product.download.price":  "¥780 買い切り · $4.99",
    "product.download.btn":    "App Storeでダウンロード",
    "product.compat.title":    "動作条件",
  }

  /*
   * ── To add a new language (e.g. Simplified Chinese) ──────────────────────
   * 1. Add  zh: { ... }  here with all keys from the en block above.
   * 2. In each HTML file add one button to .lang-switcher:
   *      <button class="lang-btn" data-lang="zh" data-i18n="lang.zh">中文</button>
   * 3. Add "lang.zh": "中文" to each language block above.
   * No other files need to change.
   */
};

/* ─── Language resolution ───────────────────────────────────────────────────── */
function resolveLanguage() {
  const param = new URLSearchParams(window.location.search).get("lang");
  if (param && TRANSLATIONS[param]) return param;

  const stored = localStorage.getItem("rs_lang");
  if (stored && TRANSLATIONS[stored]) return stored;

  for (const tag of (navigator.languages ?? [navigator.language])) {
    const base = tag.split("-")[0].toLowerCase();
    if (TRANSLATIONS[base]) return base;
  }

  return "en";
}

/* ─── Apply translations to DOM ─────────────────────────────────────────────── */
function applyTranslations(lang) {
  const dict = TRANSLATIONS[lang] ?? TRANSLATIONS["en"];

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.dataset.i18n;
    if (dict[key] !== undefined) el.textContent = dict[key];
  });

  document.querySelectorAll("[data-i18n-html]").forEach(el => {
    const key = el.dataset.i18nHtml;
    if (dict[key] !== undefined) el.innerHTML = dict[key];
  });

  document.querySelectorAll("[data-i18n-attr]").forEach(el => {
    const [attr, key] = el.dataset.i18nAttr.split(":");
    if (dict[key] !== undefined) el.setAttribute(attr, dict[key]);
  });

  document.querySelectorAll("[data-i18n-title]").forEach(el => {
    const key = el.dataset.i18nTitle;
    if (dict[key] !== undefined) document.title = dict[key];
  });

  document.documentElement.lang = lang;

  document.querySelectorAll(".lang-btn").forEach(btn => {
    const active = btn.dataset.lang === lang;
    btn.classList.toggle("lang-btn--active", active);
    btn.setAttribute("aria-pressed", String(active));
  });
}

/* ─── Switch language ────────────────────────────────────────────────────────── */
function switchLanguage(lang) {
  localStorage.setItem("rs_lang", lang);
  const url = new URL(window.location.href);
  url.searchParams.set("lang", lang);
  history.replaceState(null, "", url);
  applyTranslations(lang);
}

/* ─── Init ───────────────────────────────────────────────────────────────────── */
document.addEventListener("DOMContentLoaded", () => {
  const lang = resolveLanguage();
  applyTranslations(lang);

  document.querySelectorAll(".lang-btn").forEach(btn => {
    btn.addEventListener("click", () => switchLanguage(btn.dataset.lang));
  });
});
